export interface OrderType {
	almacen_deno: string
	almacen_pk: string
	autoriza: string
	año: string
	cant_cancelada: string
	cantidad: string
	centro: string
	cinco_al_millar: string
	cod_art_mc_pk: string
	cod_art_mc_pr: string
	cod_bar_mc_pr: string
	condiciones_pago: string
	descripcion: string
	elabora: string
	estado_ord: string
	estado_ped: string
	fecha_envio: string
	fecha_limite: string
	fecha_ord: string
	fecha_pedido: string
	fondeo_ord: string
	fondeo_ped: string
	id_cont_deta_pk: string
	id_contrato_pk: string
	id_evento: string
	id_orden_deta_pk: string
	id_orden_pk: string
	id_pedi_deta_pk: string
	id_pedido_pk: string
	iva: string
	iva_ord: string
	iva_ped: string
	jefe_division: string
	licitacion: string
	monto_ieps: string
	no_orden: string
	no_ped: string
	nuevas: string
	num_licitacion: string
	num_uh: string
	og_ord: string
	og_ped: string
	orden_Detalle_pk: string
	orden_pk: string
	pedidos_cabpk: string
	porciento_ieps: string
	precio: string
	prog_ord: string
	prog_ped: string
	proveedo_nom: string
	proveedo_pk: string
	servicio_ord: string
	servicio_ped: string
	solicitante: string
	subtotal_ord: string
	subtotal_ped: string
	suministro_ord: string
	suministro_ped: string
	tiempo_entrega: string
	tipo: string
	total_ord: string
	total_ped: string
	uh: string
	uh_corto: string
	uh_ord: string
	ur_ord: string
	ur_ped: string
	usuario_pk_ord: string
	usuario_pk_ped: string
}
