export interface SufficienciesType {
	AR: string
	EJE: string
	FIN: string
	FUN: string
	Fuen_Espe_Fina: string
	MPIO: string
	REGION: string
	SECTOR: string
	SUB_FUN: string
	TEMA: string
	UEG: string
	UP: string
	UR: string
	adjudicado: string
	alm_art_desc: string
	anio: string
	cant_lici: string
	cantidad: string
	cod_art_mc_pk: string
	cod_bar_mc_pr: string
	componente: string
	concepto: string
	contabilizable: string
	corta: string
	cost_lici: string
	costo: string
	desc_stat: string
	desc_uh: string
	descrip: string
	destino: string
	fech_alta: string
	fech_cier: string
	folio: string
	fuente: string
	id_cent: string
	id_deta_sufi: string
	id_pres: string
	id_sufi: string
	impuesto2: string
	iva: string
	partida: string
	pre_Fuen_Espe_Fina: string
	pre_destino: string
	pre_fuente: string
	presupuesto: string
	prog_pres: string
	status: string
	tipo_gasto: string
	tipo_sufu: string
	tota_lici: string
	total: string
	unid_hosp: string
	usua_alta: string
}
